# Generated by Django 5.2.9 on 2025-12-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('user_type', models.CharField(choices=[('client', 'Client (Looking for developers)'), ('developer', 'Developer (Looking for projects)')], default='client', max_length=10)),
                ('major', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('joined_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CreateUser',
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
