# Generated by Django 5.2.9 on 2025-12-29 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0002_usermd_delete_createuser_delete_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermd',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermd',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usermd',
            name='major',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermd',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client (Looking for developers)'), ('developer', 'Developer (Looking for projects)')], default='developer', max_length=10),
        ),
    ]
