# Generated by Django 5.2.9 on 2025-12-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0003_alter_usermd_address_alter_usermd_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermd',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
