# Generated by Django 5.2.9 on 2025-12-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0005_usermd_groups_usermd_is_superuser_usermd_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermd',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
